steps:
  - name: node:lts
    entrypoint: yarn
    args: []

  - name: node:lts
    entrypoint: yarn
    args: ["build"]

  - name: gcr.io/cloud-builders/gsutil
    args: [
        "-m",
        "rsync",
        "-r",
        "-c",
        "-d",
        "./docroot",
        "gs://explore.paradigm.market",
      ]

options:
 machineType: "N1_HIGHCPU_8"
